name: Workshop
on:
  push:
  workflow_dispatch:

jobs:
  ubuntu-minimal:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - uses: eessi/github-action-eessi@v3
      with:
        eessi_stack_version: '2025.06'
    - name: Test EESSI
      run: |
        module avail
      shell: bash
      